# Generated by Django 5.1.3 on 2024-11-16 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalComponent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('component_type', models.CharField(choices=[('compensation', 'Compensation'), ('deduction', 'Deduction')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalComponentConditions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('min_money', models.IntegerField(default=0)),
                ('max_money', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('all', 'All')], max_length=20)),
                ('amount', models.CharField(max_length=10)),
                ('global_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='globalConditions', to='employee_app.globalcomponent')),
            ],
        ),
    ]
