# Generated by Django 5.1.3 on 2024-11-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0002_globalcomponent_globalcomponentconditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalcomponentconditions',
            name='max_money',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='globalcomponentconditions',
            name='min_money',
            field=models.IntegerField(),
        ),
    ]
