# Generated by Django 5.1.3 on 2024-11-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0003_alter_globalcomponentconditions_max_money_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalcomponentconditions',
            name='min_amount',
            field=models.IntegerField(default=0),
        ),
    ]
