# Generated by Django 5.1.3 on 2024-11-19 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0004_globalcomponentconditions_min_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('employee_type', models.CharField(max_length=50)),
                ('relegion', models.CharField(choices=[('islam', 'Islam'), ('hindu', 'Hindu'), ('christian', 'Christian'), ('other', 'Other')], max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('job_grade', models.CharField(max_length=20)),
                ('basic_pay', models.IntegerField()),
                ('on_leave', models.BooleanField(default=False)),
                ('skip_loan', models.BooleanField(default=False)),
                ('payroll', models.BooleanField(default=True)),
                ('image_url', models.TextField(default=None, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employee_app.department')),
            ],
        ),
    ]
