# Generated by Django 5.1.3 on 2024-11-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0006_alter_employee_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image_url',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
