# Generated by Django 5.1.3 on 2024-11-24 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0007_alter_employee_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomComponent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('component_type', models.CharField(choices=[('compensation', 'Compensation'), ('deduction', 'Deduction')], max_length=30)),
                ('amount', models.IntegerField()),
                ('dsc', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_app.employee')),
            ],
        ),
    ]
